type: aws-sns-topic

description: "Provision AWS SNS Topic with serverless components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    required: true
    default: sns-${self.instanceId}
    description: The name of your SNS topic
    displayName: SNS Topic Name
    example: my-project-sns-${self.instanceId}
  displayName:
    type: string
    required: false
    displayName: SNS Topic Display Name
    description: The display name of your SNS topic
    example: My SNS Topic display name
  policy:
    type: object
    required: false
    displayName: SNS Policy
    description: The policy for your SNS topic
    example:
      Version: "2008-10-17"
      Id: policy_id
      Statement:
      - Effect: Allow
        Sid: statement_id
        Principal:
          AWS: "*"
        Action:
          - SNS:Publish
          - SNS:RemovePermission
          - SNS:SetTopicAttributes
          - SNS:DeleteTopic
          - SNS:ListSubscriptionsByTopic
          - SNS:GetTopicAttributes
          - SNS:Receive
          - SNS:AddPermission
          - SNS:Subscribe
        Resource: arn:aws:sns:us-east-1:000000000000:my-sns-topic
        Condition:
          StringEquals:
            AWS:SourceOwner: "000000000000"
  deliveryPolicy:
    type: object
    required: false
    displayName: SNS Delivery Policy
    description: The delivery policy for your SNS topic
    example:
      http:
        defaultHealthyRetryPolicy:
          minDelayTarget: 20
          maxDelayTarget: 20
          numRetries: 3
          numMaxDelayRetries: 0
          numNoDelayRetries: 0
          numMinDelayRetries: 2
          backoffFunction: linear
        disableSubscriptionOverrides: true
        defaultThrottlePolicy:
          maxReceivesPerSecond: 3

outputTypes:
  arn:
    type: string
    description: The topic arn
