name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      region: us-east-1
#
#compute:
#  type: AwsLambdaCompute
#  inputs:
#    provider: ${this.providers.aws}
#    runtime: nodejs
#
#functions:
#  hello:
#    compute: ${this.compute}
#    handler: index.hello
#    code: ./code
#    memory: 1024
#    timeout: 20
#    ufs: true

components:
  role:
    type: AwsIamRole
    inputs:
      provider: ${this.providers.aws}
      roleName: some-new-role-name
      service: elasticmapreduce.amazonaws.com
