extends: Service
name: example-service

description: Connects a Lambda function to an SNS topic using a subscription

components:
  myS3Bucket:
    type: AwsS3Bucket
    # inputs:
    #   ...
  mySNSTopic:
    type: AwsSNSTopic
    # inputs:
    #   ...
  mySubscription:
    type: Subscription
    inputs:
      source: ${myS3Bucket}
      sink: ${mySNSTopic}
      config:
        event: s3:ObjectCreated:*
        filter:
          - prefix: avatars/
          - suffix: .png
