extends: Service
name: example-service

description: Connects a Google Cloud PubSub Topic to a Google Cloud Function using a subscription

components:
  myPubSubTopic:
    type: GoogleCloudPubSubTopic
    # inputs:
    #   ...
  myCloudFunction:
    type: GoogleCloudFunction
    # inputs:
    #   ...
    mySubscription:
      type: Subscription
      inputs:
        source: ${myPubSubTopic}
        sink: ${myCloudFunction}
        config:
          event: google.pubsub.topic.publish
