export { default as debug } from './debug'
export { default as error } from './error'
export { default as info } from './info'
export { default as log } from './log'
export { default as warn } from './warn'
