type: github-webhook
version: 0.2.0
core: 0.2.x

description: "Serverless component that provisions github webhooks"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  githubApiToken:
    type: string
    required: true
    displayName: GitHub API Token
    description: |
      GitHub personal access token needed for access to the github API.
      [Create a token](https://github.com/settings/tokens)
    example: 2c5acc7de3b140ser3114fd40a24vd5ie3d843b5
  githubRepo:
    type: string
    required: true
    displayName: Github Repository
    description: The GitHub repos URL
    example: https://github.com/serverless/components/
  payloadUrl:
    type: string
    required: true
    displayName: Payload Url
    example: https://your-webhook-url-to-trigger-from-repo.com/
  events:
    type: array
    required: true
    displayName: GitHub webhook events
    description: |
      What type of event(s) will trigger the webhook URL.
      List of allowed events. For more details on events & payloads [see the docs](https://developer.github.com/v3/activity/events/types/)
    example:
      - create

outputTypes:
  github:
    type: object
    description: The GitHub Webhook configuration
